"""
RMG Gesture Classifier — Gemma3 Vision (12B / 27B)
====================================================
Designed for Google Colab Pro (A100 40 GB VRAM).

Models:
  google/gemma-3-12b-it   ~6 GB INT4  — fits any GPU
  google/gemma-3-27b-it   ~14 GB INT4 — fits A100 40 GB

Both are GATED — accept the licence at huggingface.co/google/gemma-3-12b-it
(or 27b-it) and pass your HF token via --hf-token.

SETUP — run once in Colab before this script:
  from google.colab import drive; drive.mount('/content/drive')
  !pip install -q transformers accelerate bitsandbytes numpy matplotlib pillow

Usage (delta mode — heatmaps only, 11 images/call):
  !python rmg_gemma3.py --model google/gemma-3-12b-it \\
      --mode delta --position nominal --n 100 \\
      --delta-dir "/content/drive/MyDrive/.../Heatmaps/Nominal" \\
      --results-dir "/content/drive/MyDrive/.../rmg_results_gemma3" \\
      --hf-token hf_xxx \\
      --hf-cache "/content/drive/MyDrive/hf_cache"

Usage (combined mode — heatmap + freq plot pairs, 22 images/call):
  !python rmg_gemma3.py --model google/gemma-3-12b-it \\
      --mode combined --position nominal --n 100 \\
      --delta-dir "/content/drive/MyDrive/.../Heatmaps/Nominal" \\
      --freq-dir  "/content/drive/MyDrive/.../rmg_freq_nominal" \\
      --results-dir "/content/drive/MyDrive/.../rmg_results_gemma3" \\
      --hf-token hf_xxx \\
      --hf-cache "/content/drive/MyDrive/hf_cache"
"""
from __future__ import annotations

import argparse, csv, json, os, re, random, time
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
from transformers import (
    Gemma3ForConditionalGeneration,
    AutoProcessor,
    BitsAndBytesConfig,
)

# ── CONSTANTS ─────────────────────────────────────────────────────────────────
MODEL_NAME     = "google/gemma-3-12b-it"
MAX_NEW_TOKENS = 512
REF_ITER       = 5
TEMPERATURE    = 0.5   # 0 = greedy (fixation risk); 0.3-0.7 = sampling (breaks fixation)

POSITION_FOLDERS = {
    "nominal":  "Nominal",
    "minus3cm": "Minus3cm",
    "plus3cm":  "Plus3cm",
}

ALL_GESTURES = [
    "fist", "grasp", "open_palm", "pinch", "point",
    "shaka", "thumbs_up", "twist", "wrist_down", "wrist_up",
]

_GESTURE_LIST = ", ".join(ALL_GESTURES)

# ── PROMPT ────────────────────────────────────────────────────────────────────
SYSTEM_PROMPT = f"""You are classifying hand gestures from RF S-parameter delta plots generated by the RMG (Radio-based Motion/Gesture) dataset.
A calibrated 2-port RF antenna system operating across ~2.5–3.5 GHz is placed near a participant's forearm.
For each gesture recording, the S-parameters measured during the gesture are subtracted from the participant's own "relaxed" baseline (open hand, naturally hanging) at the same arm position.
This produces ΔS plots that isolate the gesture's electromagnetic fingerprint.

Critical framing rule: relaxed is the zero-reference — it is NOT a classification target and will NEVER appear as an output label.
S12 and S21 are transmission parameters (primary information rows); S11 and S22 are reflection parameters (secondary).

Input: Two Plot Types (Provided Together)
Plot Type 1 — Delta Heatmap
Dual-panel figure: title format {{Participant}} | {{arm}}_{{position}} | iter {{N}} | Δ vs relaxed baseline.
Left panel — ΔMagnitude (RdBu): Y-axis = S11/S12/S21/S22 rows each labelled [±X dB]; X-axis = frequency ~2.5–3.5 GHz. Red = more than relaxed, Blue = less, White = no change.
Right panel — ΔPhase (coolwarm ±180°): mostly grey; vivid stripes = resonance crossing.

Plot Type 2 — Delta Frequency Plot
ΔMagnitude (dB) vs frequency. Blue trace = ΔS12, orange = ΔS21 (usually track together). Dashed 0 dB = relaxed. Y-axis range is key: deep nulls compress to −30 dB; small gestures stay within ±2 dB.

WARNING — colorbar scale is auto-normalised per image. A ±0.5 dB image and a ±5 dB image can represent completely different gestures — bracket scale matters, absolute colour saturation does not.

Cross-cutting caveat: colour polarity (red vs blue) can flip between participants for the same gesture due to differing body coupling. Always weight shape, null depth, bracket scale, and frequency morphology over absolute colour polarity.

Reasoning Protocol

STEP 1 — Note position from title (Nominal / Minus3cm / Plus3cm).
Minus3cm: some signatures invert. Plus3cm: deep nulls become asymmetric — sharp null then positive lobe; phase shows vivid narrow stripes.

STEP 2 — Screen for deep nulls.
A sharp V-shaped drop below −15 dB in ΔS12/ΔS21 means wrist_up or wrist_down — no other gesture reaches this depth. Null centred ≤ 2.9 GHz and deeper (−25 to −30 dB) → wrist_up; centred ≥ 3.0 GHz and shallower (−15 to −22 dB) → wrist_down. At Plus3cm the null becomes asymmetric with an immediate positive lobe on the high-frequency side, but the centre-frequency rule still applies. No null present → all remaining gestures stay above −10 dB; proceed to Step 3.

STEP 3 — Bracket scale + colour.
A bracket ≥ ±5 dB with deep uniform blue darkening toward high frequencies is fist (small ~+1 dB hump near 2.65 GHz confirms it) or wrist_up (resolved in Step 2). A bracket of ~±3–5 dB with light, nearly uniform blue and a near-flat frequency curve is thumbs_up. A bracket of ~±2–4 dB with moderate blue and smooth decline but no null is wrist_down (Step 2 confirmed) or open_palm. A bracket of ~±1.5–3 dB with broad red across most of the band narrows to open_palm, grasp, or shaka. A bracket below ±1.5 dB with a blue-to-red colour transition from low to high frequency and noisy traces within ±2 dB points to pinch, point, or twist.

STEP 4 — Resolve within group.
Blue group (fist / thumbs_up / wrist_down): thumbs_up = near-flat, quietest; fist = small +1 dB hump at 2.65 GHz then decline; wrist_down = confirmed null.
Red group (open_palm / grasp / shaka): shaka = narrow blue sliver at low-freq edge before red zone, S22 warm patch; open_palm = broad red, mild trough at ~3.0 GHz; grasp = like open_palm but shallower trough, red extends to low-freq edge.
Transition group (pinch / point / twist): pinch = smallest bracket ≤ ±1 dB, most oscillatory; point = slightly larger ~±1.3 dB, marginally more coherent; twist = trough shifts to 3.2–3.4 GHz, bracket ~±1.5–2 dB.

STEP 5 — Phase tiebreaker.
Mostly grey = no information. Broad warm/cool in S12/S21 = consistent phase lead/lag. Sharp vivid red-then-blue stripe at one frequency = resonance crossing (wrist gestures at off-nominal positions).

Valid gestures: {_GESTURE_LIST}

Respond with this exact block:

CLASSIFICATION: <gesture label>
CONFIDENCE: <high | medium | low>

KEY EVIDENCE:
  - Null present: <yes/no>, depth: <dB>, center: <GHz>
  - Bracket scale: <±X dB>
  - Color pattern: <uniform blue / uniform red / blue→red / mixed>
  - Frequency shape: <V-null / monotonic decline / hump / near-flat / mixed>
  - Position effect: <brief note>

RULING OUT:
  Nearest alternative: <label>
  Reason eliminated: <key difference>
"""


def _make_user_prompt_delta(gesture_order: list[str]) -> str:
    ref_lines = "\n".join(
        f"  Image {i+1:>2}: Reference — {g}" for i, g in enumerate(gesture_order))
    n = len(gesture_order)
    return (
        f"Reference images (Images 1–{n}):\n{ref_lines}\n"
        f"  Image {n+1:>2}: TEST — unknown gesture.\n\n"
        f"Apply the reasoning protocol from your instructions to classify the TEST image.\n"
        f"Valid gesture names: {_GESTURE_LIST}"
    )


def _make_user_prompt_combined(gesture_order: list[str]) -> str:
    lines = []
    for i, g in enumerate(gesture_order):
        base = i * 2
        lines.append(f"  Images {base+1:>2}-{base+2}: Reference — {g}  (heatmap, freq plot)")
    n     = len(gesture_order)
    t_idx = n * 2
    return (
        "Reference pairs (odd = delta heatmap, even = frequency plot):\n"
        + "\n".join(lines) + "\n"
        f"  Images {t_idx+1:>2}-{t_idx+2}: TEST — unknown gesture  (heatmap, freq plot)\n\n"
        f"Apply the reasoning protocol from your instructions to classify the TEST pair.\n"
        f"Valid gesture names: {_GESTURE_LIST}"
    )


# ── MODEL ─────────────────────────────────────────────────────────────────────
def load_model(model_name: str, load_in_4bit: bool = True):
    if not torch.cuda.is_available():
        raise SystemExit("[ERROR] No CUDA GPU detected.")

    props    = torch.cuda.get_device_properties(0)
    total_gb = props.total_memory / 1e9
    free_gb  = (props.total_memory - torch.cuda.memory_allocated()) / 1e9
    print(f"  GPU    : {torch.cuda.get_device_name(0)}")
    print(f"  VRAM   : {total_gb:.1f} GB total  /  {free_gb:.1f} GB free")

    kwargs: dict = {"device_map": "auto"}
    if load_in_4bit:
        kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )
        print("  Quantization : INT4 bitsandbytes")
    else:
        kwargs["torch_dtype"] = torch.bfloat16
        print("  Quantization : BF16 (full precision)")

    print(f"  Loading {model_name} ...")
    model     = Gemma3ForConditionalGeneration.from_pretrained(model_name, **kwargs).eval()
    processor = AutoProcessor.from_pretrained(model_name)

    used_gb = torch.cuda.memory_allocated() / 1e9
    print(f"  VRAM used after load: {used_gb:.1f} GB\n")
    return model, processor


# ── INFERENCE ─────────────────────────────────────────────────────────────────
def infer(model, processor, image_paths: list[Path], user_text: str) -> str:
    # Gemma3 processor expects image paths embedded in message content blocks,
    # not passed as a separate kwarg.  It handles loading internally.
    content = [{"type": "image", "image": str(p)} for p in image_paths]
    content.append({"type": "text", "text": user_text})

    messages = [
        {"role": "system", "content": [{"type": "text", "text": SYSTEM_PROMPT}]},
        {"role": "user",   "content": content},
    ]

    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    ).to(model.device, dtype=torch.bfloat16)

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=TEMPERATURE > 0,
            temperature=TEMPERATURE if TEMPERATURE > 0 else 1.0,
        )

    trimmed = [out[len(inp):] for inp, out in zip(inputs.input_ids, output_ids)]
    return processor.batch_decode(trimmed, skip_special_tokens=True)[0]


# ── PARSING ───────────────────────────────────────────────────────────────────
def extract_result(raw: str) -> dict | None:
    known = set(ALL_GESTURES)
    _cmap = {"high": 0.9, "medium": 0.65, "low": 0.35}

    # Allow optional angle brackets: <open_palm> or open_palm
    cls_m  = re.search(r"CLASSIFICATION:\s*<?([a-zA-Z_]+)>?", raw)
    conf_m = re.search(r"CONFIDENCE:\s*<?(high|medium|low)>?", raw, re.IGNORECASE)

    if cls_m:
        gesture = cls_m.group(1).strip().lower()
        if gesture in known:
            conf_label = conf_m.group(1).lower() if conf_m else "medium"
            ruling = re.search(
                r"Nearest alternative:.*?\n.*?Reason eliminated:\s*(.+)", raw, re.DOTALL)
            reasoning = ruling.group(1).strip()[:200] if ruling else ""
            return {
                "gesture":           gesture,
                "confidence":        _cmap.get(conf_label, 0.65),
                "confidence_label":  conf_label,
                "reasoning":         reasoning,
            }

    # JSON fallback
    cleaned = re.sub(r"```(?:json)?|```", "", raw).strip()
    s, e    = cleaned.find("{"), cleaned.rfind("}")
    if s == -1 or e <= s:
        return None
    try:
        parsed = json.loads(cleaned[s:e + 1])
    except json.JSONDecodeError:
        return None
    g = parsed.get("predicted_gesture") or parsed.get("gesture")
    if not g or g.lower() not in known:
        return None
    conf_raw = parsed.get("confidence", 0.0)
    if isinstance(conf_raw, str):
        conf_label = conf_raw.lower().strip()
        conf       = _cmap.get(conf_label, 0.5)
    else:
        conf       = round(max(0.0, min(1.0, float(conf_raw) if float(conf_raw) <= 1
                                        else float(conf_raw) / 100)), 4)
        conf_label = ""
    return {"gesture": g.lower(), "confidence": conf,
            "confidence_label": conf_label,
            "reasoning": parsed.get("reasoning", "")}


# ── FILE COLLECTION ───────────────────────────────────────────────────────────
def parse_delta_filename(png: Path) -> dict | None:
    if " " in png.name:
        return None
    parts    = png.stem.split("_")
    iter_tok = next((p for p in parts if p.startswith("iter")), "iter0")
    try:
        iteration = int(iter_tok.replace("iter", ""))
    except ValueError:
        iteration = 0
    return {
        "participant": parts[0] if parts else "",
        "side":        parts[1] if len(parts) > 1 else "",
        "iteration":   iteration,
    }


def collect_delta(image_dir: Path) -> list[dict]:
    known  = set(ALL_GESTURES)
    images = []
    for gdir in sorted(image_dir.iterdir()):
        if not gdir.is_dir() or gdir.name not in known:
            continue
        for png in sorted(gdir.glob("*_delta_heatmap.png")):
            meta = parse_delta_filename(png)
            if meta is None:
                continue
            images.append({**meta, "gesture": gdir.name, "path": png})
    print(f"  Found {len(images)} delta heatmap images in {image_dir.name}/")
    return images


def build_delta_refs(image_dir: Path) -> dict[tuple[str, str], Path]:
    known = set(ALL_GESTURES)
    refs: dict[tuple[str, str], Path] = {}
    for gdir in sorted(image_dir.iterdir()):
        if not gdir.is_dir() or gdir.name not in known:
            continue
        for png in gdir.glob("*_delta_heatmap.png"):
            meta = parse_delta_filename(png)
            if meta and meta["iteration"] == REF_ITER:
                refs[(meta["participant"], gdir.name)] = png
    print(f"  Delta refs : {len(refs)} entries (iter{REF_ITER})")
    return refs


def build_freq_refs(freq_base: Path) -> dict[tuple[str, str], Path]:
    """(participant, gesture) → iter{REF_ITER} frequency-plot path.
    Expected filename: {participant}_*_iter{N}_freq.png  (inside gesture sub-folders)
    """
    refs: dict[tuple[str, str], Path] = {}
    known = set(ALL_GESTURES)
    for gdir in sorted(freq_base.iterdir()):
        if not gdir.is_dir() or gdir.name not in known:
            continue
        for png in sorted(gdir.glob("*_freq.png")):
            if " " in png.name:
                continue
            parts    = png.stem.split("_")
            iter_tok = next((p for p in parts if p.startswith("iter")), "iter-1")
            try:
                iteration = int(iter_tok.replace("iter", ""))
            except ValueError:
                continue
            if iteration != REF_ITER:
                continue
            participant = parts[0]
            refs[(participant, gdir.name)] = png
    print(f"  Freq refs  : {len(refs)} entries (iter{REF_ITER})")
    return refs


def find_freq_match(meta: dict, freq_base: Path) -> Path | None:
    """Return the frequency-plot file that matches a delta heatmap's metadata."""
    gesture_dir = freq_base / meta["gesture"]
    if not gesture_dir.exists():
        return None
    for pattern in (
        f"{meta['participant']}_*_iter{meta['iteration']}_freq.png",
        f"{meta['participant']}_*_iter{meta['iteration']}_delta_freq.png",
    ):
        for png in gesture_dir.glob(pattern):
            return png
    return None


# ── CLASSIFY ──────────────────────────────────────────────────────────────────
def classify(meta: dict,
             delta_refs: dict[tuple[str, str], Path],
             model, processor,
             mode: str = "delta",
             freq_refs: dict[tuple[str, str], Path] | None = None,
             freq_base: Path | None = None,
             retries: int = 3) -> dict:
    participant    = meta["participant"]
    gesture_order: list[str] = []
    d_ref_paths:   list[Path] = []
    f_ref_paths:   list[Path] = []
    missing:       list[str]  = []

    for g in ALL_GESTURES:
        key = (participant, g)
        if key not in delta_refs:
            missing.append(g)
            continue
        if mode == "combined":
            f_path = freq_refs.get(key) if freq_refs else None
            if f_path is None:
                missing.append(g)
                continue
            f_ref_paths.append(f_path)
        gesture_order.append(g)
        d_ref_paths.append(delta_refs[key])

    if missing:
        print(f"    [WARN] Missing iter{REF_ITER} refs for {participant}: {missing}")

    # ── Build flat image list ──────────────────────────────────────────────────
    if mode == "combined":
        # Interleave: heatmap, freq, heatmap, freq, …  then test heatmap + test freq
        image_paths: list[Path] = []
        for d_path, f_path in zip(d_ref_paths, f_ref_paths):
            image_paths.append(d_path)
            image_paths.append(f_path)
        image_paths.append(meta["path"])
        freq_test = find_freq_match(meta, freq_base) if freq_base else None
        if freq_test:
            image_paths.append(freq_test)
        else:
            print(f"    [WARN] No freq match for test: {meta['path'].name}")
        user_text = _make_user_prompt_combined(gesture_order)
    else:
        image_paths = d_ref_paths + [meta["path"]]
        user_text   = _make_user_prompt_delta(gesture_order)

    for attempt in range(retries):
        t0 = time.time()
        try:
            raw     = infer(model, processor, image_paths, user_text)
            parsed  = extract_result(raw)
            latency = round(time.time() - t0, 2)
            if parsed:
                return {**parsed, "latency_s": latency, "raw": raw[:200], "error": ""}
            print(f"    [WARN] Parse failed attempt {attempt+1}: {raw[:120]}")
            time.sleep(2)
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache()
            print("    [OOM] CUDA out of memory")
            return {"gesture": "error", "confidence": 0.0, "confidence_label": "",
                    "reasoning": "", "latency_s": 0.0, "raw": "", "error": "OOM"}
        except Exception as exc:
            print(f"    [ERROR] attempt {attempt+1}: {str(exc)[:120]}")
            if attempt < retries - 1:
                time.sleep(5)

    return {"gesture": "error", "confidence": 0.0, "confidence_label": "",
            "reasoning": "", "latency_s": 0.0, "raw": "", "error": "max retries"}


# ── CHECKPOINT ────────────────────────────────────────────────────────────────
def load_checkpoint(p: Path) -> dict:
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def save_checkpoint(p: Path, done: dict) -> None:
    p.write_text(json.dumps(done))


# ── RUN LOOP ──────────────────────────────────────────────────────────────────
def run(images, delta_refs, model, processor,
        model_name, position, results_dir: Path,
        mode: str = "delta",
        freq_refs: dict[tuple[str, str], Path] | None = None,
        freq_base: Path | None = None) -> None:
    results_dir.mkdir(parents=True, exist_ok=True)
    ts        = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe      = model_name.replace("/", "_").replace(".", "_")
    csv_path  = results_dir / f"{safe}_{mode}_{position}_{ts}.csv"
    ckpt_path = results_dir / f"{safe}_{mode}_{position}_checkpoint.json"

    imgs_per_call = 22 if mode == "combined" else 11
    print(f"\n  Model    : {model_name}")
    print(f"  Mode     : {mode}  ({imgs_per_call} images/call)")
    print(f"  Position : {position}")
    print(f"  Images   : {len(images)}")
    print(f"  Output   : {csv_path}\n")

    done     = load_checkpoint(ckpt_path)
    rows_out = list(done.values())
    fieldnames = ["gesture_true", "gesture_pred", "correct",
                  "confidence", "confidence_label",
                  "participant", "side", "iteration",
                  "latency_s", "reasoning", "error", "image_path"]

    correct_total = sum(1 for r in rows_out if str(r.get("correct")) == "1")
    done_total    = len(rows_out)

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows_out:
            writer.writerow({k: r.get(k, "") for k in fieldnames})

        remaining = [img for img in images if str(img["path"]) not in done]
        if done:
            print(f"  Resuming  : {len(done)} already done")
        print(f"  Remaining : {len(remaining)} images\n")

        for i, meta in enumerate(remaining):
            result  = classify(meta, delta_refs, model, processor,
                               mode=mode, freq_refs=freq_refs, freq_base=freq_base)
            pred    = result.get("gesture", "error")
            gt      = meta["gesture"]
            correct = int(pred == gt)
            correct_total += correct
            done_total    += 1

            row = {
                "gesture_true":     gt,
                "gesture_pred":     pred,
                "correct":          correct,
                "confidence":       result["confidence"],
                "confidence_label": result.get("confidence_label", ""),
                "participant":      meta["participant"],
                "side":             meta["side"],
                "iteration":        meta["iteration"],
                "latency_s":        result["latency_s"],
                "reasoning":        result["reasoning"],
                "error":            result["error"],
                "image_path":       str(meta["path"]),
            }
            writer.writerow(row)
            f.flush()
            rows_out.append(row)
            done[str(meta["path"])] = row
            save_checkpoint(ckpt_path, done)

            status  = "✓" if correct else "✗"
            running = 100.0 * correct_total / done_total
            lbl     = result.get("confidence_label", "")
            print(f"  [{i+1:>4}/{len(remaining)}] {status}  {gt:<14} → {pred:<14}  "
                  f"conf={result['confidence']:.2f}/{lbl:<6}  "
                  f"{result['latency_s']:.1f}s  (acc={running:.1f}%)")

    final_acc = 100.0 * correct_total / done_total if done_total else 0
    print(f"\n  [DONE] Accuracy : {final_acc:.2f}%  ({correct_total}/{done_total})")
    compute_report(rows_out, csv_path, model_name, position, mode)
    visualize_results(rows_out, csv_path, model_name, position, mode)
    if ckpt_path.exists():
        ckpt_path.unlink()


# ── REPORT ────────────────────────────────────────────────────────────────────
def compute_report(rows, csv_path, model_name, position, mode: str = "delta"):
    total   = len(rows)
    correct = sum(1 for r in rows if str(r["correct"]) == "1")
    per_g   = defaultdict(lambda: {"correct": 0, "total": 0})
    for r in rows:
        per_g[r["gesture_true"]]["total"]   += 1
        per_g[r["gesture_true"]]["correct"] += int(str(r["correct"]) == "1")
    confusion = defaultdict(int)
    for r in rows:
        if str(r["correct"]) != "1":
            confusion[(r["gesture_true"], r["gesture_pred"])] += 1
    lats     = [float(r["latency_s"]) for r in rows if not r.get("error")]
    mean_lat = sum(lats) / len(lats) if lats else 0.0

    lines = ["=" * 62,
             f"  REPORT — {model_name}",
             f"  Mode: {mode}  |  Position: {position}  |  ref iter{REF_ITER}",
             "=" * 62,
             f"  Overall accuracy : {100*correct/total:.2f}%  ({correct}/{total})",
             f"  Mean latency     : {mean_lat:.2f}s per image",
             f"\n  Per-gesture accuracy:",
             f"  {'Gesture':<14} {'Acc':>6}  {'Correct':>7}  {'Total':>6}",
             f"  {'─'*44}"]
    for g in ALL_GESTURES:
        d = per_g[g]
        if d["total"] == 0:
            continue
        lines.append(f"  {g:<14} {100*d['correct']/d['total']:>5.1f}%"
                     f"  {d['correct']:>7}  {d['total']:>6}")
    lines.append(f"\n  Top misclassifications:")
    for (gt, pred), cnt in sorted(confusion.items(), key=lambda x: -x[1])[:10]:
        lines.append(f"    {gt:<14} → {pred:<14}  {cnt:>3}×")
    lines.append("=" * 62)

    report = "\n".join(lines)
    print(f"\n{report}")
    txt_path = csv_path.with_suffix(".txt")
    txt_path.write_text(report)
    print(f"  Report → {txt_path}")


# ── VISUALISATION ─────────────────────────────────────────────────────────────
def visualize_results(rows, csv_path, model_name, position, mode: str = "delta"):
    g2i = {g: i for i, g in enumerate(ALL_GESTURES)}
    n_g = len(ALL_GESTURES)
    cm  = np.zeros((n_g, n_g), dtype=int)
    for r in rows:
        ti = g2i.get(r["gesture_true"],  -1)
        pi = g2i.get(r["gesture_pred"], -1)
        if ti >= 0 and pi >= 0:
            cm[ti, pi] += 1

    row_sums = cm.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1
    cm_norm = cm / row_sums.astype(float)
    overall = 100.0 * sum(1 for r in rows if str(r["correct"]) == "1") / len(rows)

    fig, ax = plt.subplots(figsize=(13, 11))
    im = ax.imshow(cm_norm, vmin=0, vmax=1, cmap="Blues", aspect="auto")
    for i in range(n_g):
        for j in range(n_g):
            val   = cm_norm[i, j]
            color = "white" if val > 0.55 else "black"
            ax.text(j, i, f"{val:.0%}\n({cm[i,j]})",
                    ha="center", va="center", fontsize=8,
                    color=color, fontweight="bold" if i == j else "normal")
    short = [g.replace("_", "\n") for g in ALL_GESTURES]
    ax.set_xticks(range(n_g)); ax.set_xticklabels(short, fontsize=9)
    ax.set_yticks(range(n_g)); ax.set_yticklabels(ALL_GESTURES, fontsize=10)
    ax.set_xlabel("Predicted Gesture", fontsize=12, labelpad=10)
    ax.set_ylabel("True Gesture",      fontsize=12, labelpad=10)
    ax.set_title(f"{model_name}  |  {mode}  |  {position}  |  ref iter{REF_ITER}  |  Acc: {overall:.1f}%",
                 fontsize=10, pad=14)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04).set_label(
        "Recall (row-normalised)", fontsize=10)
    fig.tight_layout()
    cm_path = csv_path.with_name(csv_path.stem + "_confusion_matrix.png")
    fig.savefig(cm_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Plot   → {cm_path.name}")


# ── ENTRY POINT ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="RMG Gemma3 Delta / Combined Classifier")
    parser.add_argument("--model",    default=MODEL_NAME,
                        choices=["google/gemma-3-12b-it", "google/gemma-3-27b-it"])
    parser.add_argument("--mode",     default="delta", choices=["delta", "combined"],
                        help="delta = heatmaps only (11 img/call) | "
                             "combined = heatmap+freq pairs (22 img/call)")
    parser.add_argument("--position", default="nominal",
                        choices=list(POSITION_FOLDERS.keys()))
    parser.add_argument("--delta-dir",  required=True,
                        help="Path to Heatmaps/{Position}/ folder")
    parser.add_argument("--freq-dir",   default=None,
                        help="Path to rmg_freq_{position}/ folder. "
                             "Required when --mode combined.")
    parser.add_argument("--results-dir", default="/content/rmg_results_gemma3")
    parser.add_argument("--hf-token",    required=True,
                        help="HuggingFace read token (model is gated)")
    parser.add_argument("--hf-cache",    default=None,
                        help="HuggingFace cache dir on Drive")
    parser.add_argument("--n",    type=int, default=None,
                        help="Images to classify. Default: 1 per gesture × participant.")
    parser.add_argument("--all", action="store_true",
                        help="Run on ALL test images (every iteration except iter5). "
                             "Overrides --n. Use for full-dataset evaluation.")
    parser.add_argument("--no-4bit", action="store_true",
                        help="Load in BF16 instead of INT4 (needs more VRAM)")
    parser.add_argument("--temperature", type=float, default=TEMPERATURE,
                        help="Sampling temperature. 0 = greedy (fixation risk). "
                             "0.3-0.7 = sampling (breaks fixation, spreads predictions). "
                             f"Default: {TEMPERATURE}")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    os.environ["HUGGING_FACE_HUB_TOKEN"] = args.hf_token
    os.environ["HF_TOKEN"]               = args.hf_token
    print(f"  HF token  → set ({args.hf_token[:8]}...)")

    if args.hf_cache:
        tmp_dir = args.hf_cache + "/tmp"
        Path(tmp_dir).mkdir(parents=True, exist_ok=True)
        os.environ["HF_HOME"]            = args.hf_cache
        os.environ["TRANSFORMERS_CACHE"] = args.hf_cache
        os.environ["TMPDIR"]             = tmp_dir
        os.environ["TEMP"]               = tmp_dir
        os.environ["TMP"]                = tmp_dir
        print(f"  HF cache  → {args.hf_cache}")

    TEMPERATURE = args.temperature
    random.seed(args.seed)

    delta_dir = Path(args.delta_dir)
    if not delta_dir.exists():
        raise SystemExit(f"[ERROR] Delta directory not found: {delta_dir}")

    freq_dir: Path | None = None
    if args.mode == "combined":
        if not args.freq_dir:
            raise SystemExit("[ERROR] --freq-dir is required for --mode combined.")
        freq_dir = Path(args.freq_dir)
        if not freq_dir.exists():
            raise SystemExit(f"[ERROR] Freq directory not found: {freq_dir}")

    model, processor = load_model(args.model, load_in_4bit=not args.no_4bit)

    print(f"\n── Collecting delta heatmaps: {delta_dir} ──")
    all_images = collect_delta(delta_dir)
    if not all_images:
        raise SystemExit("[ERROR] No delta heatmap images found.")

    print(f"\n── Building reference tables (iter{REF_ITER}) ──")
    delta_refs = build_delta_refs(delta_dir)
    freq_refs  = build_freq_refs(freq_dir) if args.mode == "combined" else None

    test_images = [img for img in all_images if img["iteration"] != REF_ITER]
    print(f"  Test images : {len(test_images)}  (iter{REF_ITER} excluded)")

    if args.all:
        test_images = sorted(test_images,
                             key=lambda x: (x["gesture"], x["participant"], x["iteration"]))
        print(f"  Full dataset : {len(test_images)} (all iter except iter{REF_ITER})")
    elif args.n is not None:
        by_g = defaultdict(list)
        for img in test_images:
            by_g[img["gesture"]].append(img)
        per_g   = max(1, args.n // len(by_g))
        sampled = []
        for g in sorted(by_g):
            sampled.extend(random.sample(
                sorted(by_g[g], key=lambda x: str(x["path"])),
                min(per_g, len(by_g[g]))))
        random.shuffle(sampled)
        test_images = sampled[:args.n]
        print(f"  Subsampled  : {len(test_images)} (~{per_g}/gesture)")
    else:
        by_gp = defaultdict(list)
        for img in test_images:
            by_gp[(img["gesture"], img["participant"])].append(img)
        sampled = []
        for key in sorted(by_gp):
            pool = sorted(by_gp[key], key=lambda x: x["iteration"])
            sampled.append(random.choice(pool))
        random.shuffle(sampled)
        test_images = sampled
        print(f"  Sampled     : {len(test_images)}  (1 per gesture × participant)")

    run(test_images,
        delta_refs=delta_refs,
        model=model,
        processor=processor,
        model_name=args.model,
        position=args.position,
        results_dir=Path(args.results_dir),
        mode=args.mode,
        freq_refs=freq_refs,
        freq_base=freq_dir)
