
from __future__ import annotations

import argparse, csv, json, os, re, random, time
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
from PIL import Image as _PIL_Image
import torchvision.transforms as _tv_T
from torchvision.transforms.functional import InterpolationMode as _ILM
from transformers import (
    Qwen2_5_VLForConditionalGeneration,
    Gemma3ForConditionalGeneration,
    MllamaForConditionalGeneration,
    AutoModel,
    AutoModelForCausalLM,
    AutoProcessor,
    AutoTokenizer,
    BitsAndBytesConfig,
)

_MODEL_FAMILY: str = "qwen"  # set by load_model(); controls img_block and infer paths

# ── InternVL2.5 image preprocessing ──────────────────────────────────────────
_INTERNVL_MEAN = (0.485, 0.456, 0.406)
_INTERNVL_STD  = (0.229, 0.224, 0.225)
_INTERNVL_SIZE = 448  # px; InternVL2.5 native tile resolution

def _internvl_load_image(path: Path) -> torch.Tensor:
    """Return [1, 3, 448, 448] float32 tensor for one image (single tile)."""
    transform = _tv_T.Compose([
        _tv_T.Lambda(lambda img: img.convert("RGB")),
        _tv_T.Resize((_INTERNVL_SIZE, _INTERNVL_SIZE), interpolation=_ILM.BICUBIC),
        _tv_T.ToTensor(),
        _tv_T.Normalize(mean=_INTERNVL_MEAN, std=_INTERNVL_STD),
    ])
    return transform(_PIL_Image.open(path)).unsqueeze(0)  # [1, 3, H, W]

# ── CONFIG — edit DRIVE_ROOT if your Drive layout differs ─────────────────────
#
# Set DRIVE_ROOT to the folder on Drive that contains Code/ and Results/.
# Examples:
#   /content/drive/MyDrive/Semester Project
#   /content/drive/MyDrive/Aalborg University 2nd Semester/Semester Project
#
DRIVE_ROOT = Path("/content/drive/MyDrive/Semester Project")

ACTIVE_MODEL    = "Qwen/Qwen2.5-VL-72B-Instruct"
ACTIVE_MODE     = "combined"     # "delta" or "combined"
ACTIVE_POSITION = "minus3cm"
LOAD_IN_4BIT    = True
MAX_NEW_TOKENS  = 512
REF_ITER        = 5
TEMPERATURE     = 0.5   # 0 = greedy (fixation risk); 0.3–0.7 = sampling (breaks fixation)

# Pixels per image passed to Qwen2.5-VL processor.
# Lower = fewer visual tokens = shorter context.  Higher = more detail.
# 256×28×28 ≈ 200 K pixels (≈448×448).  512×28×28 ≈ 400 K pixels (≈632×632).
REF_MAX_PIXELS  = 256 * 28 * 28   # reference images (need overall shape, not fine detail)
TEST_MAX_PIXELS = 512 * 28 * 28   # test images (benefit from more detail)

POSITION_FOLDERS = {
    "nominal":  "Nominal",
    "minus3cm": "Minus3cm",
    "plus3cm":  "Plus3cm",
}

ALL_GESTURES = [
    "fist", "grasp", "open_palm", "pinch", "point",
    "shaka", "thumbs_up", "twist", "wrist_down", "wrist_up",
]

# Derived paths — no need to change these if DRIVE_ROOT is correct
BASE_DELTA_DIR = DRIVE_ROOT / "Results/delta_plots/Test_Sample/Heatmaps"
BASE_FREQ_DIR  = DRIVE_ROOT / "Results/Images_VLM/PerPosition"
RESULTS_DIR    = DRIVE_ROOT / "Code/VLM_Classification/rmg_results_delta_colab"

# ── PROMPTS ───────────────────────────────────────────────────────────────────
_GESTURE_LIST = ", ".join(ALL_GESTURES)

SYSTEM_PROMPT_COMBINED = f"""You are classifying hand gestures from RF S-parameter delta plots generated by the RMG (Radio-based Motion/Gesture) dataset.
A calibrated 2-port RF antenna system operating across ~2.5–3.5 GHz is placed near a participant's forearm.
For each gesture recording, the S-parameters measured during the gesture are subtracted from the participant's own "relaxed" baseline (open hand, naturally hanging) at the same arm position.
This produces ΔS plots that isolate the gesture's electromagnetic fingerprint.

Critical framing rule: relaxed is the zero-reference — it is NOT a classification target and will NEVER appear as an output label.
S12 and S21 are transmission parameters (primary information rows); S11 and S22 are reflection parameters (secondary).

Input: Two Plot Types (Provided Together)
Plot Type 1 — Delta Heatmap
Dual-panel figure: title format {{Participant}} | {{arm}}_{{position}} | iter {{N}} | Δ vs relaxed baseline.
Left panel — ΔMagnitude (RdBu): Y-axis = S11/S12/S21/S22 rows each labelled [±X dB]; X-axis = frequency ~2.5–3.5 GHz. Red = more than relaxed, Blue = less, White = no change.
Right panel — ΔPhase (coolwarm ±180°): mostly grey; vivid stripes = resonance crossing.

Plot Type 2 — Delta Frequency Plot
ΔMagnitude (dB) vs frequency. Blue trace = ΔS12, orange = ΔS21 (usually track together). Dashed 0 dB = relaxed. Y-axis range is key: deep nulls compress to −30 dB; small gestures stay within ±2 dB.

WARNING — colorbar scale is auto-normalised per image. A ±0.5 dB image and a ±5 dB image can represent completely different gestures — bracket scale matters, absolute colour saturation does not.

Cross-cutting caveat: colour polarity (red vs blue) can flip between participants for the same gesture due to differing body coupling. Always weight shape, null depth, bracket scale, and frequency morphology over absolute colour polarity.

Reasoning Protocol

STEP 1 — Note position from title (Nominal / Minus3cm / Plus3cm).
Minus3cm: some signatures invert. Plus3cm: deep nulls become asymmetric — sharp null then positive lobe; phase shows vivid narrow stripes.

STEP 2 — Screen for deep nulls.
A sharp V-shaped drop below −15 dB in ΔS12/ΔS21 means wrist_up or wrist_down — no other gesture reaches this depth. Null centred ≤ 2.9 GHz and deeper (−25 to −30 dB) → wrist_up; centred ≥ 3.0 GHz and shallower (−15 to −22 dB) → wrist_down. At Plus3cm the null becomes asymmetric with an immediate positive lobe on the high-frequency side, but the centre-frequency rule still applies. No null present → all remaining gestures stay above −10 dB; proceed to Step 3.

STEP 3 — Bracket scale + colour.
A bracket ≥ ±5 dB with deep uniform blue darkening toward high frequencies is fist (small ~+1 dB hump near 2.65 GHz confirms it) or wrist_up (resolved in Step 2). A bracket of ~±3–5 dB with light, nearly uniform blue and a near-flat frequency curve is thumbs_up. A bracket of ~±2–4 dB with moderate blue and smooth decline but no null is wrist_down (Step 2 confirmed) or open_palm. A bracket of ~±1.5–3 dB with broad red across most of the band narrows to open_palm, grasp, or shaka. A bracket below ±1.5 dB with a blue-to-red colour transition from low to high frequency and noisy traces within ±2 dB points to pinch, point, or twist.

STEP 4 — Resolve within group.
Blue group (fist / thumbs_up / wrist_down): thumbs_up = near-flat, quietest; fist = small +1 dB hump at 2.65 GHz then decline; wrist_down = confirmed null.
Red group (open_palm / grasp / shaka): shaka = narrow blue sliver at low-freq edge before red zone, S22 warm patch; open_palm = broad red, mild trough at ~3.0 GHz; grasp = like open_palm but shallower trough, red extends to low-freq edge.
Transition group (pinch / point / twist): pinch = smallest bracket ≤ ±1 dB, most oscillatory; point = slightly larger ~±1.3 dB, marginally more coherent; twist = trough shifts to 3.2–3.4 GHz, bracket ~±1.5–2 dB.

STEP 5 — Phase tiebreaker.
Mostly grey = no information. Broad warm/cool in S12/S21 = consistent phase lead/lag. Sharp vivid red-then-blue stripe at one frequency = resonance crossing (wrist gestures at off-nominal positions).

Valid gestures: {_GESTURE_LIST}

Respond with this exact block:

CLASSIFICATION: <gesture label>
CONFIDENCE: <high | medium | low>

KEY EVIDENCE:
  - Null present: <yes/no>, depth: <dB>, center: <GHz>
  - Bracket scale: <±X dB>
  - Color pattern: <uniform blue / uniform red / blue→red / mixed>
  - Frequency shape: <V-null / monotonic decline / hump / near-flat / mixed>
  - Position effect: <brief note>

RULING OUT:
  Nearest alternative: <label>
  Reason eliminated: <key difference>
"""

def make_user_prompt_delta(gesture_order: list[str]) -> str:
    ref_lines = "\n".join(
        f"  Image {i+1:>2}: Reference — {g}" for i, g in enumerate(gesture_order)
    )
    n = len(gesture_order)
    return (
        f"Reference images (Images 1–{n}):\n{ref_lines}\n"
        f"  Image {n+1:>2}: TEST — unknown gesture.\n\n"
        f"Apply the reasoning protocol from your instructions to classify the TEST image.\n"
        f"Valid gesture names: {_GESTURE_LIST}"
    )


def make_user_prompt_combined(gesture_order: list[str]) -> str:
    lines = []
    for i, g in enumerate(gesture_order):
        base = i * 2
        lines.append(f"  Images {base+1:>2}-{base+2}: Reference — {g}  (heatmap, freq plot)")
    n     = len(gesture_order)
    t_idx = n * 2
    return (
        f"Reference pairs (odd = delta heatmap, even = frequency plot):\n"
        + "\n".join(lines) + "\n"
        f"  Images {t_idx+1:>2}-{t_idx+2}: TEST — unknown gesture  (heatmap, freq plot)\n\n"
        f"Apply the reasoning protocol from your instructions to classify the TEST pair.\n"
        f"Valid gesture names: {_GESTURE_LIST}"
    )


# ── MODEL LOADING ─────────────────────────────────────────────────────────────
def load_model(model_name: str, load_in_4bit: bool, max_gpu_memory_gib: float | None = None):
    global _MODEL_FAMILY
    mn = model_name.lower()
    is_gemma    = "gemma"    in mn
    is_internvl = "internvl" in mn
    is_llama_v  = "llama"    in mn and "vision" in mn

    if is_gemma:
        _MODEL_FAMILY = "gemma"
    elif is_internvl:
        _MODEL_FAMILY = "internvl"
    elif is_llama_v:
        _MODEL_FAMILY = "llama_vision"
    else:
        _MODEL_FAMILY = "qwen"

    print(f"\n  Loading {model_name} ...")
    print(f"  Family       : {_MODEL_FAMILY.upper()}")

    if load_in_4bit:
        print(f"  Quantization : INT4 bitsandbytes")
    else:
        print(f"  Quantization : bfloat16 (full precision)")

    if torch.cuda.is_available():
        props    = torch.cuda.get_device_properties(0)
        total_gb = props.total_memory / 1e9
        free_gb  = (props.total_memory - torch.cuda.memory_allocated()) / 1e9
        print(f"  GPU          : {torch.cuda.get_device_name(0)}")
        print(f"  VRAM total   : {total_gb:.1f} GB")
        print(f"  VRAM free    : {free_gb:.1f} GB")
        if free_gb < 5.0:
            raise SystemExit(
                f"[ERROR] Only {free_gb:.1f} GB VRAM free before model load — GPU is dirty.\n"
                "  → In Colab: Runtime → Disconnect and delete runtime → reconnect."
            )
    else:
        raise SystemExit("[ERROR] No CUDA GPU — switch to GPU runtime in Colab.")

    kwargs: dict = {"device_map": "auto"}
    if max_gpu_memory_gib is not None:
        kwargs["max_memory"] = {0: f"{max_gpu_memory_gib:.0f}GiB", "cpu": "80GiB"}
        print(f"  GPU cap      : {max_gpu_memory_gib:.0f} GiB  (overflow → CPU RAM)")
    if load_in_4bit:
        kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )
    else:
        kwargs["torch_dtype"] = torch.bfloat16

    if is_internvl:
        # device_map="auto" is incompatible with InternVL2.5: its __init__ calls
        # .item() on linspace tensors before weights are materialized from meta device.
        # Load directly in BF16 and move to GPU manually instead.
        iv_kwargs: dict = {"trust_remote_code": True, "torch_dtype": torch.bfloat16}
        if "quantization_config" in kwargs:
            iv_kwargs["quantization_config"] = kwargs["quantization_config"]
        model = AutoModel.from_pretrained(model_name, **iv_kwargs).eval().cuda()
        processor = AutoTokenizer.from_pretrained(
            model_name, trust_remote_code=True)
    elif is_llama_v:
        model = MllamaForConditionalGeneration.from_pretrained(model_name, **kwargs)
        processor = AutoProcessor.from_pretrained(model_name)
    elif is_gemma:
        model = Gemma3ForConditionalGeneration.from_pretrained(model_name, **kwargs)
        processor = AutoProcessor.from_pretrained(model_name)
    else:  # qwen
        model = Qwen2_5_VLForConditionalGeneration.from_pretrained(model_name, **kwargs)
        processor = AutoProcessor.from_pretrained(model_name)

    used_gb = torch.cuda.memory_allocated() / 1e9
    print(f"  VRAM used after load: {used_gb:.1f} GB\n")
    return model, processor


# ── INFERENCE ─────────────────────────────────────────────────────────────────
def infer(model, processor, messages: list[dict]) -> str:

    if _MODEL_FAMILY == "internvl":
        # ── InternVL2.5 path ──────────────────────────────────────────────────
        # Extract system text and user content from standard message structure
        system_text = next(
            (m["content"] for m in messages if m["role"] == "system"
             and isinstance(m["content"], str)), "")
        user_msg = next(m for m in messages if m["role"] == "user")

        image_paths: list[Path] = []
        user_text = ""
        for c in user_msg["content"]:
            if c.get("type") == "image":
                image_paths.append(Path(c["image"]))
            elif c.get("type") == "text":
                user_text = c["text"]

        # Preprocess images → [N, 3, 448, 448] bfloat16 on GPU
        pv_list = [_internvl_load_image(p) for p in image_paths]
        pixel_values = torch.cat(pv_list, dim=0).to(model.device, dtype=torch.bfloat16)
        num_patches_list = [1] * len(image_paths)  # 1 tile per image (no dynamic tiling)

        # Build question: system instruction inline + image tokens + user prompt
        image_tokens = "<image>\n" * len(image_paths)
        question = (f"{system_text}\n\n" if system_text else "") + image_tokens + user_text

        gen_config = dict(max_new_tokens=MAX_NEW_TOKENS, do_sample=False)
        response = model.chat(
            processor, pixel_values, question, gen_config,
            num_patches_list=num_patches_list,
        )
        return response

    if _MODEL_FAMILY == "llama_vision":
        # ── Llama-3.2-Vision path ─────────────────────────────────────────────
        # Processor takes PIL images separately from the text messages.
        # Content blocks use {"type": "image"} with no path — images passed as list.
        llama_messages: list[dict] = []
        pil_images: list = []

        for m in messages:
            if m["role"] == "system":
                sys_text = m["content"] if isinstance(m["content"], str) else ""
                if sys_text:
                    llama_messages.append({"role": "system", "content": sys_text})
            elif m["role"] == "user":
                llama_content: list[dict] = []
                for c in m["content"]:
                    if c.get("type") == "image":
                        pil_images.append(_PIL_Image.open(c["image"]).convert("RGB"))
                        llama_content.append({"type": "image"})
                    elif c.get("type") == "text":
                        llama_content.append({"type": "text", "text": c["text"]})
                llama_messages.append({"role": "user", "content": llama_content})

        input_text = processor.apply_chat_template(
            llama_messages, add_generation_prompt=True)
        inputs = processor(
            images=pil_images, text=input_text, return_tensors="pt"
        ).to(model.device)
        with torch.no_grad():
            output_ids = model.generate(
                **inputs, max_new_tokens=MAX_NEW_TOKENS, do_sample=False)
        return processor.decode(
            output_ids[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)

    if _MODEL_FAMILY == "gemma":
        # Gemma3 expects system content as a list of text blocks
        msgs = []
        for m in messages:
            if m["role"] == "system" and isinstance(m["content"], str):
                msgs.append({"role": "system", "content": [{"type": "text", "text": m["content"]}]})
            else:
                msgs.append(m)
        inputs = processor.apply_chat_template(
            msgs,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt",
        ).to(model.device, dtype=torch.bfloat16)
        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=TEMPERATURE > 0,
                temperature=TEMPERATURE if TEMPERATURE > 0 else 1.0,
            )
        return processor.decode(
            output_ids[0][inputs["input_ids"].shape[-1]:],
            skip_special_tokens=True,
        )

    # Qwen path
    from qwen_vl_utils import process_vision_info
    text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    ).to("cuda")
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=TEMPERATURE > 0,
            temperature=TEMPERATURE if TEMPERATURE > 0 else None,
            top_p=None,
        )
    trimmed = [out[len(inp):] for inp, out in zip(inputs.input_ids, output_ids)]
    return processor.batch_decode(trimmed, skip_special_tokens=True)[0]


# ── JSON PARSING ──────────────────────────────────────────────────────────────
def extract_json(raw: str) -> dict | None:
    """Parse model output — handles both structured CLASSIFICATION: format and JSON."""
    known  = set(ALL_GESTURES)
    _cmap  = {"high": 0.9, "medium": 0.65, "low": 0.35}

    # ── Primary: structured format (CLASSIFICATION: / CONFIDENCE: / RULING OUT:) ──
    # Allow optional angle brackets: model sometimes outputs <open_palm> vs open_palm
    cls_match  = re.search(r"CLASSIFICATION:\s*<?([a-zA-Z_]+)>?", raw)
    conf_match = re.search(r"CONFIDENCE:\s*<?(high|medium|low)>?", raw, re.IGNORECASE)
    if cls_match:
        gesture = cls_match.group(1).strip().lower()
        if gesture in known:
            conf_label = conf_match.group(1).lower() if conf_match else "medium"
            # Extract ruling-out line as reasoning
            ruling = re.search(r"Nearest alternative:.*?\n.*?Reason eliminated:\s*(.+)", raw, re.DOTALL)
            reasoning = ruling.group(1).strip()[:200] if ruling else ""
            return {
                "gesture":           gesture,
                "predicted_gesture": gesture,
                "confidence":        _cmap.get(conf_label, 0.65),
                "confidence_label":  conf_label,
                "reasoning":         reasoning,
            }

    # ── Fallback: JSON format ──
    cleaned = re.sub(r"```(?:json)?|```", "", raw).strip()
    s, e    = cleaned.find("{"), cleaned.rfind("}")
    if s == -1 or e <= s:
        return None
    try:
        parsed = json.loads(cleaned[s:e + 1])
    except json.JSONDecodeError:
        return None
    if "predicted_gesture" in parsed:
        parsed["gesture"] = parsed["predicted_gesture"]
    if "gesture" not in parsed:
        return None
    conf_raw = parsed.get("confidence", 0.0)
    if isinstance(conf_raw, str):
        parsed["confidence_label"] = conf_raw.lower().strip()
        parsed["confidence"]       = _cmap.get(conf_raw.lower().strip(), 0.5)
    else:
        try:
            conf = float(conf_raw)
            parsed["confidence"] = round(max(0.0, min(1.0, conf if conf <= 1 else conf / 100)), 4)
        except (TypeError, ValueError):
            parsed["confidence"] = 0.0
        parsed["confidence_label"] = ""
    parsed.setdefault("reasoning", "")
    return parsed


# ── IMAGE HELPERS ─────────────────────────────────────────────────────────────
def img_block(path: Path, max_pixels: int) -> dict:
    """Single image content block. InternVL/Gemma/Llama ignore max_pixels (handled in infer)."""
    if _MODEL_FAMILY in ("gemma", "internvl", "llama_vision"):
        return {"type": "image", "image": str(path)}
    return {"type": "image", "image": str(path), "max_pixels": max_pixels}


# ── FILE COLLECTION ───────────────────────────────────────────────────────────
def parse_delta_filename(png: Path) -> dict | None:
    """Parse {participant}_{side}_{position}_iter{N}_delta_heatmap.png"""
    if " " in png.name:
        return None
    parts    = png.stem.split("_")
    iter_tok = next((p for p in parts if p.startswith("iter")), "iter0")
    try:
        iteration = int(iter_tok.replace("iter", ""))
    except ValueError:
        iteration = 0
    return {
        "participant": parts[0] if len(parts) > 0 else "",
        "side":        parts[1] if len(parts) > 1 else "",
        "iteration":   iteration,
    }


def collect_delta(image_dir: Path) -> list[dict]:
    images = []
    known  = set(ALL_GESTURES)
    for gesture_dir in sorted(image_dir.iterdir()):
        if not gesture_dir.is_dir() or gesture_dir.name not in known:
            continue
        gesture = gesture_dir.name
        for png in sorted(gesture_dir.glob("*_delta_heatmap.png")):
            meta = parse_delta_filename(png)
            if meta is None:
                continue
            images.append({
                "gesture":     gesture,
                "participant": meta["participant"],
                "side":        meta["side"],
                "iteration":   meta["iteration"],
                "path":        png,
            })
    print(f"  Found {len(images)} delta heatmap images in {image_dir.name}/")
    return images


def build_delta_refs(image_dir: Path) -> dict[tuple[str, str], Path]:
    """(participant, gesture) → iter{REF_ITER} delta path."""
    refs: dict[tuple[str, str], Path] = {}
    known = set(ALL_GESTURES)
    for gesture_dir in sorted(image_dir.iterdir()):
        if not gesture_dir.is_dir() or gesture_dir.name not in known:
            continue
        for png in gesture_dir.glob("*_delta_heatmap.png"):
            meta = parse_delta_filename(png)
            if meta and meta["iteration"] == REF_ITER:
                refs[(meta["participant"], gesture_dir.name)] = png
    print(f"  Delta refs   : {len(refs)} entries (iter{REF_ITER})")
    return refs


def build_freq_refs(freq_base: Path, position: str) -> dict[tuple[str, str], Path]:
    """(participant, gesture) → iter{REF_ITER} freq path.
    Freq filename: {participant}_{gesture}_{side}_{position}_iter{N}_freq.png
    """
    refs: dict[tuple[str, str], Path] = {}
    known = set(ALL_GESTURES)
    for gesture_dir in sorted(freq_base.iterdir()):
        if not gesture_dir.is_dir() or gesture_dir.name not in known:
            continue
        for png in sorted(gesture_dir.glob("*_freq.png")):
            if " " in png.name:
                continue
            parts    = png.stem.split("_")
            iter_tok = next((p for p in parts if p.startswith("iter")), "iter-1")
            try:
                iteration = int(iter_tok.replace("iter", ""))
            except ValueError:
                continue
            if iteration != REF_ITER:
                continue
            participant = parts[0]
            refs[(participant, gesture_dir.name)] = png
    print(f"  Freq refs    : {len(refs)} entries (iter{REF_ITER})")
    return refs


def find_freq_match(meta: dict, freq_base: Path) -> Path | None:
    """Find the freq plot that exactly matches a delta heatmap's metadata."""
    gesture_dir = freq_base / meta["gesture"]
    if not gesture_dir.exists():
        return None
    # Support both *_iter{N}_freq.png and *_iter{N}_delta_freq.png naming
    for pattern in (
        f"{meta['participant']}_*_iter{meta['iteration']}_freq.png",
        f"{meta['participant']}_*_iter{meta['iteration']}_delta_freq.png",
    ):
        for png in gesture_dir.glob(pattern):
            return png
    return None


# ── CLASSIFY ONE TEST IMAGE ───────────────────────────────────────────────────
def classify(meta: dict,
             delta_refs: dict[tuple[str, str], Path],
             freq_refs:  dict[tuple[str, str], Path] | None,
             freq_base:  Path | None,
             model,
             processor,
             mode: str,
             retries: int = 3) -> dict:
    participant = meta["participant"]

    gesture_order: list[str] = []
    d_ref_paths: list[Path]  = []
    f_ref_paths: list[Path]  = []
    missing: list[str]       = []

    for g in ALL_GESTURES:
        key = (participant, g)
        if key not in delta_refs:
            missing.append(g)
            continue
        if mode == "combined":
            f_path = freq_refs.get(key) if freq_refs else None
            if f_path is None:
                missing.append(g)
                continue
            f_ref_paths.append(f_path)
        gesture_order.append(g)
        d_ref_paths.append(delta_refs[key])

    if missing:
        print(f"    [WARN] Missing iter{REF_ITER} refs for {participant}: {missing}")

    # Build content list
    content: list[dict] = []
    if mode == "combined":
        for d_path, f_path in zip(d_ref_paths, f_ref_paths):
            content.append(img_block(d_path, REF_MAX_PIXELS))
            content.append(img_block(f_path, REF_MAX_PIXELS))
        content.append(img_block(meta["path"], TEST_MAX_PIXELS))
        freq_test = find_freq_match(meta, freq_base) if freq_base else None
        if freq_test:
            content.append(img_block(freq_test, TEST_MAX_PIXELS))
        else:
            print(f"    [WARN] No freq match for test: {meta['path'].name}")
        user_prompt = make_user_prompt_combined(gesture_order)
        system_prompt = SYSTEM_PROMPT_COMBINED
    else:
        for d_path in d_ref_paths:
            content.append(img_block(d_path, REF_MAX_PIXELS))
        content.append(img_block(meta["path"], TEST_MAX_PIXELS))
        user_prompt   = make_user_prompt_delta(gesture_order)
        system_prompt = SYSTEM_PROMPT_COMBINED

    content.append({"type": "text", "text": user_prompt})

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": content},
    ]

    for attempt in range(retries):
        t0 = time.time()
        try:
            raw     = infer(model, processor, messages)
            parsed  = extract_json(raw)
            latency = round(time.time() - t0, 2)
            if parsed:
                return {**parsed, "latency_s": latency, "raw": raw[:200], "error": ""}
            print(f"    [WARN] Bad JSON attempt {attempt+1}: {raw[:120]}")
            time.sleep(2)
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache()
            print("    [OOM] CUDA out of memory — try --no-4bit=False or a smaller model")
            return {"gesture": "error", "confidence": 0.0, "confidence_label": "",
                    "reasoning": "", "latency_s": 0.0, "raw": "", "error": "OOM"}
        except Exception as e:
            err = str(e)
            print(f"    [ERROR] attempt {attempt+1}: {err[:120]}")
            if attempt < retries - 1:
                time.sleep(5)

    return {"gesture": "error", "confidence": 0.0, "confidence_label": "",
            "reasoning": "", "latency_s": 0.0, "raw": "", "error": "max retries"}


# ── CHECKPOINT ────────────────────────────────────────────────────────────────
def load_checkpoint(ckpt_path: Path) -> dict[str, dict]:
    if not ckpt_path.exists():
        return {}
    try:
        with open(ckpt_path) as f:
            return json.load(f)
    except Exception:
        return {}


def save_checkpoint(ckpt_path: Path, done: dict[str, dict]) -> None:
    with open(ckpt_path, "w") as f:
        json.dump(done, f)


# ── MAIN RUN LOOP ─────────────────────────────────────────────────────────────
def run(images:       list[dict],
        delta_refs:   dict[tuple[str, str], Path],
        freq_refs:    dict[tuple[str, str], Path] | None,
        freq_base:    Path | None,
        model,
        processor,
        model_name:   str,
        position:     str,
        mode:         str) -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = model_name.replace("/", "_").replace(".", "_")
    csv_path  = RESULTS_DIR / f"{safe_name}_{mode}_{position}_{timestamp}.csv"
    ckpt_path = RESULTS_DIR / f"{safe_name}_{mode}_{position}_checkpoint.json"

    imgs_per_call = 24 if mode == "combined" else 12
    print(f"\n  Model       : {model_name}")
    print(f"  Mode        : {mode}  ({imgs_per_call} images/call)")
    print(f"  Position    : {position}")
    print(f"  Reference   : iter{REF_ITER}")
    print(f"  Images      : {len(images)}")
    print(f"  Cost        : $0.00  (local inference)")
    print(f"  Output      : {csv_path}")
    print(f"  Checkpoint  : {ckpt_path}")

    done = load_checkpoint(ckpt_path)
    if done:
        print(f"  Resuming    : {len(done)} images already done")

    fieldnames = ["gesture_true", "gesture_pred", "correct",
                  "confidence", "confidence_label",
                  "participant", "side", "iteration",
                  "latency_s", "reasoning", "error", "image_path"]

    rows_out: list[dict] = list(done.values())

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows_out:
            writer.writerow({k: r.get(k, "") for k in fieldnames})

        remaining = [img for img in images if str(img["path"]) not in done]
        n         = len(remaining)
        print(f"  Remaining   : {n} images\n")

        correct_total = sum(1 for r in rows_out if str(r.get("correct")) == "1")
        done_total    = len(rows_out)

        for i, meta in enumerate(remaining):
            result  = classify(meta, delta_refs, freq_refs, freq_base,
                               model, processor, mode)
            pred    = result.get("gesture", "error")
            gt      = meta["gesture"]
            correct = int(pred == gt)
            correct_total += correct
            done_total    += 1

            row = {
                "gesture_true":     gt,
                "gesture_pred":     pred,
                "correct":          correct,
                "confidence":       result["confidence"],
                "confidence_label": result.get("confidence_label", ""),
                "participant":      meta["participant"],
                "side":             meta["side"],
                "iteration":        meta["iteration"],
                "latency_s":        result["latency_s"],
                "reasoning":        result["reasoning"],
                "error":            result["error"],
                "image_path":       str(meta["path"]),
            }
            writer.writerow(row)
            f.flush()
            rows_out.append(row)
            done[str(meta["path"])] = row
            save_checkpoint(ckpt_path, done)

            status  = "✓" if correct else "✗"
            running = 100.0 * correct_total / done_total
            lbl     = result.get("confidence_label", "")
            print(f"  [{i+1:>4}/{n}] {status}  {gt:<14} → {pred:<14}  "
                  f"conf={result['confidence']:.2f}/{lbl:<6}  "
                  f"{result['latency_s']:.1f}s  (acc={running:.1f}%)")

    final_acc = 100.0 * correct_total / done_total if done_total else 0
    print(f"\n  [DONE] Accuracy : {final_acc:.2f}%  ({correct_total}/{done_total})")

    compute_report(rows_out, csv_path, model_name, position, mode)
    visualize_results(rows_out, csv_path, model_name, position, mode)

    if ckpt_path.exists():
        ckpt_path.unlink()


# ── REPORT ────────────────────────────────────────────────────────────────────
def compute_report(rows: list[dict], csv_path: Path,
                   model_name: str, position: str, mode: str) -> None:
    total   = len(rows)
    correct = sum(1 for r in rows if str(r["correct"]) == "1")

    per_g: dict[str, dict] = defaultdict(lambda: {"correct": 0, "total": 0})
    for r in rows:
        per_g[r["gesture_true"]]["total"]   += 1
        per_g[r["gesture_true"]]["correct"] += int(str(r["correct"]) == "1")

    confusion: dict[tuple, int] = defaultdict(int)
    for r in rows:
        if str(r["correct"]) != "1":
            confusion[(r["gesture_true"], r["gesture_pred"])] += 1

    lats     = [float(r["latency_s"]) for r in rows if not r.get("error")]
    mean_lat = sum(lats) / len(lats) if lats else 0.0

    lines = ["=" * 62,
             f"  REPORT — {model_name}",
             f"  Mode: {mode}  |  Position: {position}  |  ref iter{REF_ITER}",
             f"  Local inference (HuggingFace transformers) — no API cost",
             "=" * 62,
             f"  Overall accuracy : {100*correct/total:.2f}%  ({correct}/{total})",
             f"  Mean latency     : {mean_lat:.2f}s per image",
             f"\n  Per-gesture accuracy:",
             f"  {'Gesture':<14} {'Acc':>6}  {'Correct':>7}  {'Total':>6}",
             f"  {'─'*44}"]
    for g in ALL_GESTURES:
        d = per_g[g]
        if d["total"] == 0:
            continue
        lines.append(f"  {g:<14} {100*d['correct']/d['total']:>5.1f}%"
                     f"  {d['correct']:>7}  {d['total']:>6}")

    lines.append(f"\n  Top misclassifications:")
    for (gt, pred), cnt in sorted(confusion.items(), key=lambda x: -x[1])[:10]:
        lines.append(f"    {gt:<14} → {pred:<14}  {cnt:>3}×")
    lines.append("=" * 62)

    report = "\n".join(lines)
    print(f"\n{report}")
    txt_path = csv_path.with_suffix(".txt")
    txt_path.write_text(report)
    print(f"  Report → {txt_path}")


# ── VISUALISATION ─────────────────────────────────────────────────────────────
def visualize_results(rows: list[dict], csv_path: Path,
                      model_name: str, position: str, mode: str) -> None:
    g2i = {g: i for i, g in enumerate(ALL_GESTURES)}
    n_g = len(ALL_GESTURES)
    cm  = np.zeros((n_g, n_g), dtype=int)
    for r in rows:
        ti = g2i.get(r["gesture_true"], -1)
        pi = g2i.get(r["gesture_pred"], -1)
        if ti >= 0 and pi >= 0:
            cm[ti, pi] += 1

    row_sums = cm.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1
    cm_norm  = cm / row_sums.astype(float)
    overall  = 100.0 * sum(1 for r in rows if str(r["correct"]) == "1") / len(rows)

    fig, ax = plt.subplots(figsize=(13, 11))
    im = ax.imshow(cm_norm, vmin=0, vmax=1, cmap="Blues", aspect="auto")
    for i in range(n_g):
        for j in range(n_g):
            val   = cm_norm[i, j]
            color = "white" if val > 0.55 else "black"
            ax.text(j, i, f"{val:.0%}\n({cm[i,j]})",
                    ha="center", va="center", fontsize=8,
                    color=color, fontweight="bold" if i == j else "normal")
    short = [g.replace("_", "\n") for g in ALL_GESTURES]
    ax.set_xticks(range(n_g)); ax.set_xticklabels(short, fontsize=9)
    ax.set_yticks(range(n_g)); ax.set_yticklabels(ALL_GESTURES, fontsize=10)
    ax.set_xlabel("Predicted Gesture", fontsize=12, labelpad=10)
    ax.set_ylabel("True Gesture",      fontsize=12, labelpad=10)
    ax.set_title(
        f"{model_name}  |  {mode}  |  {position}  |  ref iter{REF_ITER}  |  Acc: {overall:.1f}%",
        fontsize=10, pad=14,
    )
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04).set_label(
        "Recall (row-normalised)", fontsize=10)
    fig.tight_layout()
    cm_path = csv_path.with_name(csv_path.stem + "_confusion_matrix.png")
    fig.savefig(cm_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Plot → {cm_path.name}")


# ── ENTRY POINT ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="RMG Qwen2.5-VL Colab — Delta / Combined Classifier")
    parser.add_argument("--model", default=ACTIVE_MODEL,
                        help=f"HuggingFace model ID (default: {ACTIVE_MODEL})")
    parser.add_argument("--mode", default=ACTIVE_MODE, choices=["delta", "combined"],
                        help="delta = heatmaps only (12 img/call) | "
                             "combined = heatmap+freq pairs (24 img/call)")
    parser.add_argument("--position", default=ACTIVE_POSITION,
                        choices=list(POSITION_FOLDERS.keys()))
    parser.add_argument("--delta-dir", default=None,
                        help="Direct path to Heatmaps/{Position}/ folder "
                             "(e.g. /content/drive/MyDrive/Test_Sample/Heatmaps/Minus3cm). "
                             "Overrides --drive-root for delta images.")
    parser.add_argument("--freq-dir", default=None,
                        help="Direct path to rmg_freq_{position}/ folder. "
                             "Overrides --drive-root for freq images. Required for --mode combined.")
    parser.add_argument("--results-dir", default="/content/rmg_results_delta_colab",
                        help="Where to save CSV, report, and confusion matrix.")
    parser.add_argument("--hf-cache", default=None,
                        help="Override HuggingFace cache dir. Set to a Drive path to avoid "
                             "using Colab local disk (e.g. /content/drive/MyDrive/hf_cache).")
    parser.add_argument("--hf-token", default=None,
                        help="HuggingFace read token for gated models "
                             "(e.g. meta-llama/Llama-3.2-11B-Vision-Instruct). "
                             "Get yours at https://huggingface.co/settings/tokens")
    parser.add_argument("--drive-root", default=str(DRIVE_ROOT),
                        help="Project root on Drive (used only if --delta-dir is not set).")
    parser.add_argument("--n", type=int, default=None,
                        help="Images to classify. Default: 1 per (gesture × participant).")
    parser.add_argument("--all", action="store_true",
                        help="Run on ALL test images (every iteration except iter5). "
                             "Overrides --n. Use for full-dataset evaluation.")
    parser.add_argument("--no-4bit", action="store_true",
                        help="Use bfloat16 instead of INT4 (needs more VRAM)")
    parser.add_argument("--temperature", type=float, default=TEMPERATURE,
                        help="Sampling temperature. 0 = greedy (fixation risk). "
                             "0.3–0.7 = sampling (breaks fixation). "
                             f"Default: {TEMPERATURE}")
    parser.add_argument("--max-gpu-memory", type=float, default=None,
                        help="Cap GPU usage in GiB and spill overflow to CPU RAM "
                             "(e.g. 20 for 32B on A100 40 GB). Inference will be slower.")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    # HuggingFace token (required for gated models like Llama-3.2-Vision)
    if args.hf_token:
        os.environ["HUGGING_FACE_HUB_TOKEN"] = args.hf_token
        os.environ["HF_TOKEN"]               = args.hf_token
        print(f"  HF token     → set ({args.hf_token[:8]}...)")

    # Redirect HuggingFace cache AND temp staging to Drive BEFORE any model loading
    if args.hf_cache:
        import os
        tmp_dir = args.hf_cache + "/tmp"
        Path(tmp_dir).mkdir(parents=True, exist_ok=True)
        os.environ["HF_HOME"]            = args.hf_cache
        os.environ["TRANSFORMERS_CACHE"] = args.hf_cache
        os.environ["HF_DATASETS_CACHE"]  = args.hf_cache
        os.environ["TMPDIR"]             = tmp_dir  # HF stages downloads here before moving to cache
        os.environ["TEMP"]               = tmp_dir
        os.environ["TMP"]                = tmp_dir
        print(f"  HF cache → {args.hf_cache}")
        print(f"  TMPDIR   → {tmp_dir}")

    TEMPERATURE = args.temperature
    random.seed(args.seed)

    RESULTS_DIR = Path(args.results_dir)

    pos_folder = POSITION_FOLDERS[args.position]

    if args.delta_dir:
        delta_dir = Path(args.delta_dir)
    else:
        drive_root = Path(args.drive_root)
        delta_dir  = drive_root / "Results/delta_plots/Test_Sample/Heatmaps" / pos_folder

    if args.freq_dir:
        freq_dir = Path(args.freq_dir)
    else:
        drive_root = Path(args.drive_root)
        freq_dir   = drive_root / "Results/Images_VLM/PerPosition" / f"rmg_freq_{args.position}"

    if not delta_dir.exists():
        raise SystemExit(f"[ERROR] Delta directory not found: {delta_dir}\n"
                         "Use --delta-dir to point directly to the Heatmaps/Minus3cm folder.")

    if args.mode == "combined" and not freq_dir.exists():
        raise SystemExit(f"[ERROR] Freq directory not found: {freq_dir}\n"
                         "Use --freq-dir or switch to --mode delta.")

    model, processor = load_model(args.model, load_in_4bit=not args.no_4bit,
                                   max_gpu_memory_gib=args.max_gpu_memory)

    print(f"\n── Collecting delta heatmaps: {delta_dir} ──")
    all_images = collect_delta(delta_dir)
    if not all_images:
        raise SystemExit("[ERROR] No delta heatmap images found.")

    print(f"\n── Building reference tables (iter{REF_ITER}) ──")
    delta_refs = build_delta_refs(delta_dir)
    freq_refs  = build_freq_refs(freq_dir, args.position) if args.mode == "combined" else None

    test_images = [img for img in all_images if img["iteration"] != REF_ITER]
    print(f"  Test images  : {len(test_images)}  (iter{REF_ITER} excluded)")

    if args.all:
        test_images = sorted(test_images,
                             key=lambda x: (x["gesture"], x["participant"], x["iteration"]))
        print(f"  Full dataset : {len(test_images)} (all iter except iter{REF_ITER})")
    elif args.n is not None:
        by_g: dict = defaultdict(list)
        for img in test_images:
            by_g[img["gesture"]].append(img)
        per_g  = max(1, args.n // len(by_g))
        sampled: list = []
        for g in sorted(by_g):
            sampled.extend(random.sample(
                sorted(by_g[g], key=lambda x: str(x["path"])),
                min(per_g, len(by_g[g]))))
        random.shuffle(sampled)
        test_images = sampled[:args.n]
        print(f"  Subsampled   : {len(test_images)} (~{per_g}/gesture)")
    else:
        by_gp: dict = defaultdict(list)
        for img in test_images:
            by_gp[(img["gesture"], img["participant"])].append(img)
        sampled = []
        for key in sorted(by_gp):
            pool = sorted(by_gp[key], key=lambda x: x["iteration"])
            sampled.append(random.choice(pool))
        random.shuffle(sampled)
        test_images = sampled
        print(f"  Sampled      : {len(test_images)}  (1 per gesture × participant)")

    run(test_images,
        delta_refs=delta_refs,
        freq_refs=freq_refs,
        freq_base=freq_dir if args.mode == "combined" else None,
        model=model,
        processor=processor,
        model_name=args.model,
        position=args.position,
        mode=args.mode)
